const ZERO_UNDER_POINTS_STAND = 50;
const ZERO_OVER_POINTS_STAND = 25;
const ZERO_UNDER_POINTS_FAIL = -50;
const POINTS_FOR_ZERO_EXTRAHAND_UNDER = 10;
const ZERO_OVER_POINTS_FAIL = -25;
const POINTS_FOR_ZERO_EXTRAHAND_OVER = 5;
const EXTRA_POINTS_FOR_STAND = 10;
const PENALTY_PER_DIFFERENCE = -10;
const BONUS_POINTS_FOR_5_ROW = 15;

export {
    ZERO_UNDER_POINTS_STAND,
    ZERO_OVER_POINTS_STAND,
    ZERO_UNDER_POINTS_FAIL,
    POINTS_FOR_ZERO_EXTRAHAND_UNDER,
    ZERO_OVER_POINTS_FAIL,
    POINTS_FOR_ZERO_EXTRAHAND_OVER,
    EXTRA_POINTS_FOR_STAND,
    PENALTY_PER_DIFFERENCE,
    BONUS_POINTS_FOR_5_ROW
}
